package com.vmlts.service;

import com.vmlts.entity.Challenge;
import com.vmlts.entity.Lesson;
import com.vmlts.repository.ChallengeRepository;
import com.vmlts.repository.LessonRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
@Slf4j
public class DataSeederService {

    private final LessonRepository lessonRepository;
    private final ChallengeRepository challengeRepository;

    @EventListener(ApplicationReadyEvent.class)
    @Transactional
    public void seed() {
        seedLessons();
        seedChallenges();
        log.info("Database seeding complete");
    }

    private void seedLessons() {
        record L(String title, String duration, boolean premium, int order, String content, String videoId, String quiz) {}
        var lessons = new L[]{
            new L("What is Forex Trading?", "8 min", false, 1,
                "The foreign exchange market (Forex or FX) is the largest and most liquid financial market in the world, with over $7.5 trillion traded every single day — more than every stock market on earth combined. Unlike stock markets, Forex has no central exchange or physical location. It operates as a decentralised network of banks, brokers, institutions, hedge funds, and individual retail traders connected electronically across the globe.\n\nWHAT ACTUALLY HAPPENS IN A TRADE — Forex trading is the act of buying one currency while simultaneously selling another. Currencies are always quoted and traded in pairs — EUR/USD, GBP/USD, USD/JPY. If you believe the Euro will rise against the Dollar, you buy EUR/USD. If you're right, you sell it back later at a higher price and pocket the difference.\n\nMARKET PARTICIPANTS — Central banks manage currency reserves and set interest rates that move entire markets. Commercial banks handle the bulk of daily volume for clients and their own accounts. Hedge funds and institutions trade for speculative profit. Corporations exchange currency to pay for imports/exports. Retail traders like you make up a smaller but fast-growing slice of the market, trading through brokers.\n\nTRADING SESSIONS — The market is open 24 hours a day, 5 days a week, rotating through four major sessions as the sun moves around the globe: Sydney (open first), Tokyo, London, and New York. The London and New York overlap (roughly 8am-12pm EST) produces the highest volume and volatility of the day, making it the most popular window for active traders.\n\nWHY PEOPLE TRADE FOREX — Low barriers to entry (you can start with a small account), extremely high liquidity (trades execute instantly at fair prices), the ability to profit whether prices rise OR fall, and 24-hour market access make Forex attractive compared to other markets.\n\nTHE RISKS — Leverage means both gains and losses are amplified. Prices can move fast and unpredictably around news events. Most new traders lose money because they trade without a plan, risk too much per trade, or let emotions drive decisions. This is exactly why VMLTS lets you practice with a simulated account before risking real capital.\n\nFURTHER READING — This introductory module draws on the same beginner-friendly approach found in \"Currency Trading for Dummies\" (Boris Schlossberg & Kathleen Brooks) and \"Forex Trading: The Basics Explained in Simple Terms\" (Jim Brown) — both solid next reads if you want more plain-language depth before moving into the technical lessons ahead.",
                "yhAA9bmo9FY",
                "[{\"q\":\"Roughly how much is traded in the global Forex market every day?\",\"options\":[\"$7.5 million\",\"$7.5 billion\",\"$7.5 trillion\",\"$750 billion\"],\"correct\":2},{\"q\":\"Which session overlap produces the highest trading volume and volatility?\",\"options\":[\"Sydney and Tokyo\",\"Tokyo and London\",\"London and New York\",\"New York and Sydney\"],\"correct\":2},{\"q\":\"What is a key advantage of Forex trading mentioned in the lesson?\",\"options\":[\"You can only profit when prices rise\",\"The market is open 24 hours a day, 5 days a week\",\"There is no risk involved\",\"It has a single central exchange\"],\"correct\":1}]"),
            new L("Understanding Currency Pairs", "10 min", false, 2,
                "Every Forex trade involves two currencies — a currency pair. The BASE currency is listed first, the QUOTE currency second. The price tells you how much of the quote currency it takes to buy one unit of the base currency.\n\nREADING A QUOTE — Example: EUR/USD = 1.0850 means 1 Euro costs 1.0850 US Dollars. If you buy EUR/USD, you're buying Euros and selling Dollars, betting the Euro strengthens. If you sell, you're betting the Euro weakens against the Dollar.\n\nMAJORS — The most heavily traded pairs, all involving the US Dollar: EUR/USD, GBP/USD, USD/JPY, AUD/USD, USD/CAD, USD/CHF. These have the tightest spreads and highest liquidity because so many participants trade them constantly.\n\nMINORS (CROSS PAIRS) — Pairs that don't include the US Dollar, combining two other major currencies: EUR/GBP, EUR/AUD, GBP/JPY. Slightly wider spreads than majors since volume is lower.\n\nEXOTICS — One major currency paired with a currency from a smaller or emerging economy: USD/ZAR (South African Rand), EUR/TRY (Turkish Lira), USD/MXN (Mexican Peso). These carry higher spreads and can move sharply on local political or economic news.\n\nHOW PRICE MOVEMENT IS DESCRIBED — When traders say a pair is \"strong\" or \"weak,\" they mean the base currency's value relative to the quote currency. EUR/USD rising means the Euro is strengthening OR the Dollar is weakening (usually some combination of both, driven by economic data or interest rate expectations).\n\nWHY IT MATTERS FOR YOUR STRATEGY — Major pairs suit beginners because of low cost and predictable behaviour. Exotics can offer bigger moves but come with more risk and unpredictability — something to graduate into once you have experience.",
                "pExqfmDRKHw",
                "[{\"q\":\"In the pair EUR/USD, which currency is the base currency?\",\"options\":[\"USD\",\"EUR\",\"Both equally\",\"Neither\"],\"correct\":1},{\"q\":\"Which of these is classified as a major currency pair?\",\"options\":[\"USD/ZAR\",\"EUR/TRY\",\"GBP/USD\",\"EUR/GBP\"],\"correct\":2},{\"q\":\"What generally characterizes exotic currency pairs?\",\"options\":[\"Tightest spreads in the market\",\"Higher spreads and can move sharply on local news\",\"They never include a major currency\",\"They are the most liquid pairs\"],\"correct\":1}]"),
            new L("Pips, Lots and Spreads", "10 min", false, 3,
                "PIPS — A pip (\"percentage in point\") is the smallest standard price movement in Forex. For most pairs it is the 4th decimal place: 0.0001. For JPY pairs it is the 2nd decimal: 0.01. If EUR/USD moves from 1.0850 to 1.0860, that is a 10-pip move. Some brokers quote an extra \"pipette\" decimal for more precision (1.08505), but pips remain the standard unit traders talk in.\n\nLOTS — A lot is the standardised trade size in Forex. Standard Lot = 100,000 units of the base currency. Mini Lot = 10,000 units. Micro Lot = 1,000 units. In VMLTS, lot sizes like 0.01 represent a micro lot — ideal for learning without risking large swings in your simulated balance.\n\nPIP VALUE — The dollar value of each pip depends on your lot size. On a standard lot of EUR/USD, one pip is worth roughly $10. On a micro lot (0.01), one pip is worth roughly $0.10. This is why lot size directly controls how much money you make or lose per pip of movement.\n\nSPREADS — The spread is the difference between the BUY price (ask) and the SELL price (bid) that your broker quotes. This is how brokers earn revenue on \"zero-commission\" accounts. A EUR/USD bid of 1.0848 and ask of 1.0850 means a 2-pip spread — you're already 2 pips \"down\" the moment you open a trade. Tighter spreads mean cheaper, more efficient trading, which matters most for short-term/frequent traders.\n\nPUTTING IT TOGETHER — Before opening any trade, know your lot size, the resulting pip value, and the spread you're paying. A common beginner mistake is trading a lot size that's too large for the account, turning small price moves into big swings in balance.",
                "ADmSZWv8GF4",
                "[{\"q\":\"For most currency pairs, a pip refers to which decimal place?\",\"options\":[\"1st decimal\",\"2nd decimal\",\"4th decimal\",\"6th decimal\"],\"correct\":2},{\"q\":\"How many units make up a standard lot?\",\"options\":[\"1,000\",\"10,000\",\"100,000\",\"1,000,000\"],\"correct\":2},{\"q\":\"What is the spread?\",\"options\":[\"The total profit on a trade\",\"The difference between the bid and ask price\",\"The number of pips in a lot\",\"A type of leverage\"],\"correct\":1}]"),
            new L("Leverage and Margin", "12 min", false, 4,
                "Leverage allows you to control a large position with a relatively small deposit. At 100:1 leverage you control $100,000 in the market with just $1,000 of your own money. This is what makes Forex accessible with small accounts — but it's a double-edged sword: a 1% move in your favour can double your deposit, while a 1% move against you can wipe it out. Leverage amplifies both profits AND losses equally; it does not change the odds of the trade being right.\n\nMARGIN — Margin is the deposit required to open and maintain a leveraged position. At 100:1 leverage, the margin requirement is 1% of the full position size. Margin is collateral held by the broker, not a fee you pay — it's returned to you when you close the trade (adjusted for profit or loss).\n\nFREE MARGIN & EQUITY — Equity is your account balance adjusted for any open trade's floating profit or loss. Free margin is the equity not currently tied up as margin on open positions — it's what's available to open new trades or absorb losses.\n\nMARGIN CALL — If your account equity falls below the required maintenance margin (because open trades are losing), the broker will issue a margin call, and may automatically start closing your positions to prevent your balance from going negative. This is a hard stop, not a warning you can ignore.\n\nCHOOSING LEVERAGE WISELY — Just because a broker offers 500:1 leverage doesn't mean you should use it. New traders should behave as if leverage is much lower (effectively 10:1 or less) by keeping position sizes small relative to account balance, regardless of what the broker allows.\n\nIN VMLTS — margin per trade is calculated as Lot Size × Entry Price × 0.01, giving you a realistic feel for how margin requirements scale with position size.",
                "xC63HG-vB_4",
                "[{\"q\":\"At 100:1 leverage, how much margin do you need to control a $100,000 position?\",\"options\":[\"$100,000\",\"$10,000\",\"$1,000\",\"$100\"],\"correct\":2},{\"q\":\"What happens during a margin call?\",\"options\":[\"The broker gives you free extra capital\",\"Your leverage automatically increases\",\"The broker may automatically close your losing positions\",\"Your spread is reduced to zero\"],\"correct\":2},{\"q\":\"What is the key risk of using high leverage?\",\"options\":[\"It only amplifies profits, never losses\",\"It amplifies both profits and losses equally\",\"It eliminates the need for a stop loss\",\"It guarantees a margin call\"],\"correct\":1}]"),
            new L("Risk Management Basics", "12 min", false, 5,
                "THE 1-2% RULE — Never risk more than 1-2% of your account balance on a single trade. On a $1,000 account that means $10-$20 maximum risk per trade. This single rule is the biggest separator between traders who survive long enough to improve and those who blow up their account on a bad streak.\n\nSTOP LOSS — An order that automatically closes your trade if price moves a set amount against you, capping your loss at a known, pre-defined amount. Always set a stop loss before entering a trade — no exceptions, no \"I'll watch it manually.\" Markets move fast and emotions cloud judgement in the moment.\n\nTAKE PROFIT — An order that automatically closes your trade once it reaches your target profit level, removing emotion from exit decisions and locking in gains without needing to watch the screen.\n\nRISK TO REWARD (R:R) — The ratio of how much you're risking to how much you stand to gain. A 1:2 R:R means you risk $10 to potentially make $20. This matters more than most beginners realise: even winning only 40-50% of your trades, a consistent 1:2 R:R can still be profitable over time. Aim for a minimum of 1:1.5 on every trade you take.\n\nPOSITION SIZING — Your lot size should be adjusted based on how far away your stop loss is. A wider stop (more pips of room) requires a smaller lot size to keep your dollar risk within that 1-2% ceiling; a tighter stop allows a slightly larger lot size for the same dollar risk.\n\nWHY THIS COMES BEFORE STRATEGY — You can have a mediocre entry strategy and still succeed with excellent risk management. You cannot have a brilliant strategy and succeed with reckless risk management. This is the foundation everything else in trading is built on.",
                "8mRQI7euUQU",
                "[{\"q\":\"According to the 1-2% rule, how much should you risk on a single trade with a $1,000 account?\",\"options\":[\"$100-$200\",\"$50-$100\",\"$10-$20\",\"$1-$2\"],\"correct\":2},{\"q\":\"What does a 1:2 risk-to-reward ratio mean?\",\"options\":[\"You risk $20 to make $10\",\"You risk $10 to make $20\",\"You need to win 2 out of 3 trades\",\"Your stop loss is twice your take profit\"],\"correct\":1},{\"q\":\"When should you set your stop loss?\",\"options\":[\"After the trade starts losing money\",\"Only on losing trades\",\"Before entering the trade, no exceptions\",\"Stop losses are optional for experienced traders\"],\"correct\":2}]"),
            new L("Technical Analysis: Support & Resistance", "20 min", true, 6,
                "SUPPORT — A price zone where buying pressure has historically been strong enough to prevent further falls. Think of it as a floor. When price approaches support, traders watch for signs of a bounce upward.\n\nRESISTANCE — A price zone where selling pressure has historically prevented further rises. Think of it as a ceiling. When price approaches resistance, traders watch for a reversal downward.\n\nHOW TO IDENTIFY THEM — Look for price levels where the market has reversed multiple times in the past. The more times a level has been tested and held, the stronger and more significant it is considered. Swing highs tend to become resistance; swing lows tend to become support.\n\nROLE REVERSAL — When support is broken convincingly (a strong close well below the level, not just a brief wick through it), that former support often becomes new resistance — and vice versa when resistance breaks. This \"role reversal\" concept is one of the most reliable and widely used ideas in technical analysis.\n\nZONES, NOT EXACT LINES — Support and resistance are rarely a single precise price; they're better thought of as zones a few pips wide, since price often overshoots or undershoots the exact historical level before reacting.\n\nSTRATEGY — Buy near strong support with a stop loss placed just below the zone. Sell near strong resistance with a stop loss placed just above the zone. Always wait for price confirmation (a rejection candle, a bounce) before entering rather than trying to guess the exact turning point. Draw your levels on higher timeframes (Daily, 4-Hour) first, since these tend to be more significant than levels found on lower timeframes.",
                "UGj9yzUh5xI",
                "[{\"q\":\"What is support in technical analysis?\",\"options\":[\"A price zone where selling pressure prevents rises\",\"A price zone where buying pressure prevents further falls\",\"The broker's spread\",\"A type of candlestick pattern\"],\"correct\":1},{\"q\":\"What typically happens when resistance is broken convincingly?\",\"options\":[\"It disappears from the chart entirely\",\"It often becomes new support (role reversal)\",\"Price always reverses immediately\",\"The spread widens permanently\"],\"correct\":1},{\"q\":\"Which timeframes should you draw key support/resistance levels on first?\",\"options\":[\"1-minute chart\",\"5-minute chart\",\"Higher timeframes like Daily and 4-Hour\",\"It doesn't matter\"],\"correct\":2}]"),
            new L("Candlestick Patterns", "18 min", true, 7,
                "Candlestick charts originated in 18th-century Japan for tracking rice prices and were brought to Western trading audiences largely through Steve Nison's landmark book Japanese Candlestick Charting Techniques, which remains the reference text most modern candlestick education (including this lesson) traces back to.\n\nCandlestick charts show four data points per period: Open, High, Low, Close. The \"body\" of the candle shows the open-to-close range; the thin \"wicks\" (or shadows) above and below show the extremes reached during that period. Bullish candles (close higher than open) are typically shown green; bearish candles (close lower than open) are typically shown red.\n\nDOJI — Open and close are nearly equal, creating a cross or plus-sign shape. This signals indecision between buyers and sellers. Context matters: a doji forming at support often hints at a bullish reversal; one forming at resistance often hints at a bearish reversal.\n\nHAMMER — A small body sitting near the top of the candle's range with a long lower wick. It forms at the bottom of a downtrend and shows that sellers pushed price lower during the period, but buyers stepped in hard and rejected those lower prices — a bullish signal.\n\nSHOOTING STAR — The mirror image of a hammer: small body near the bottom with a long upper wick. Forms at the top of an uptrend, showing buyers pushed price higher but sellers overwhelmed them and dragged price back down — a bearish signal.\n\nBULLISH ENGULFING — A large green candle whose body completely \"engulfs\" the body of the previous red candle. This shows a decisive shift from selling to buying pressure and is a strong bullish reversal signal, especially at support.\n\nBEARISH ENGULFING — The opposite: a large red candle completely engulfing the previous green candle's body, signalling a strong bearish reversal, especially at resistance.\n\nKEY RULE — Never trade a candlestick pattern in isolation. A hammer in the middle of a sideways range means far less than a hammer forming exactly at a well-tested support level. Always confirm patterns with the broader trend direction and key price levels.\n\nFURTHER READING — For the full depth of Japanese candlestick theory, including multi-candle formations beyond what's covered here, Steve Nison's \"Japanese Candlestick Charting Techniques\" is the definitive next step.",
                "4aP0N4dP20I",
                "[{\"q\":\"What does a hammer candlestick pattern typically signal when it forms at the bottom of a downtrend?\",\"options\":[\"A bearish continuation\",\"A bullish reversal\",\"Market indecision only\",\"Increased spread\"],\"correct\":1},{\"q\":\"What defines a bullish engulfing pattern?\",\"options\":[\"A small green candle inside the previous red candle\",\"A large green candle whose body completely engulfs the previous red candle's body\",\"Two dojis in a row\",\"A long upper wick with a small body at the bottom\"],\"correct\":1},{\"q\":\"According to the key rule in this lesson, how should you trade candlestick patterns?\",\"options\":[\"In isolation, without any other confirmation\",\"Only on the 1-minute chart\",\"Always confirmed with trend direction and key levels\",\"Only during news releases\"],\"correct\":2}]"),
            new L("Moving Averages & Indicators", "22 min", true, 8,
                "MOVING AVERAGES (MA) — Moving averages smooth out price data to reveal the underlying trend direction, filtering out short-term noise.\n\nSMA (Simple Moving Average) — The average of closing prices over the last N periods, recalculated as new candles form. The 50 SMA and 200 SMA are widely watched by traders and institutions alike; price trading above the 200 SMA is generally read as a bullish long-term environment, and below it as bearish.\n\nEMA (Exponential Moving Average) — Similar to an SMA but weights recent prices more heavily, so it reacts faster to new price action. The 20 EMA and 50 EMA are popular choices for identifying dynamic, moving support and resistance in trending markets.\n\nMA CROSSOVERS — When a faster MA (like the 20 EMA) crosses above a slower MA (like the 50 EMA), it's often read as a potential shift into an uptrend (sometimes called a \"golden cross\" for longer-term MAs). Crossing below signals a potential downtrend (\"death cross\").\n\nRSI (Relative Strength Index) — Measures momentum on a scale of 0 to 100. Readings above 70 suggest the market may be overbought (due for a pullback); readings below 30 suggest oversold (due for a bounce). RSI is best used to confirm a trade idea, not as a standalone buy/sell signal.\n\nMACD (Moving Average Convergence Divergence) — Shows the relationship between two EMAs (typically 12 and 26 period) via a MACD line and signal line. When the MACD line crosses above the signal line, it's read as bullish momentum building; crossing below is read as bearish momentum building.\n\nBOLLINGER BANDS — A middle SMA with an upper and lower band plotted at two standard deviations from that average. When the bands squeeze tightly together, it often signals low volatility that precedes a big directional move.\n\nKEY TIP — More indicators is not better. Pick one or two that complement each other (e.g. a trend indicator like an EMA plus a momentum indicator like RSI) and master how they behave together, rather than cluttering your chart with everything at once.",
                "PhzO7iTBoMs",
                "[{\"q\":\"An RSI reading above 70 typically suggests the market is:\",\"options\":[\"Oversold\",\"Overbought\",\"In a strong downtrend only\",\"About to have zero volatility\"],\"correct\":1},{\"q\":\"What does an EMA do differently compared to an SMA?\",\"options\":[\"It ignores recent prices completely\",\"It weights recent prices more heavily and reacts faster\",\"It only works on JPY pairs\",\"It measures spread, not price\"],\"correct\":1},{\"q\":\"What does a Bollinger Band squeeze often signal?\",\"options\":[\"The market has permanently stopped moving\",\"Low volatility that often precedes a big directional move\",\"A guaranteed bearish reversal\",\"That RSI is broken\"],\"correct\":1}]"),
            new L("Risk Management & Position Sizing", "15 min", true, 9,
                "ADVANCED POSITION SIZING — The formula: Position Size = (Account Risk in $) ÷ (Stop Loss in pips × Pip Value).\n\nWORKED EXAMPLE — $5,000 account. Risking 1% = $50. Your stop loss is 30 pips away. Pip value at 0.01 lots is roughly $0.10. Position size = $50 ÷ (30 × $0.10) = 16.7 micro lots. This formula ensures your dollar risk stays constant regardless of how wide or tight your stop loss is on any given setup.\n\nDAILY RISK LIMITS — Set a maximum daily loss limit (commonly 3-5% of account balance). If you hit it, stop trading for the day entirely. Chasing losses with bigger, more emotional trades — \"revenge trading\" — is one of the fastest ways to blow up an account.\n\nCORRELATED PAIRS — EUR/USD and GBP/USD often move in the same direction because both are quoted against the US Dollar and influenced by similar macro drivers. Trading both simultaneously in the same direction effectively doubles your real exposure to a single underlying risk (USD strength or weakness), even though it looks like two separate trades.\n\nTRAILING STOPS — A stop loss that automatically moves with price as a trade goes in your favour, locking in progressively more profit while still giving the trade room to breathe rather than exiting at the first sign of a pullback.\n\nSCALING IN AND OUT — More advanced traders often enter a partial position at the first signal and add to it on confirmation, then take partial profits at an initial target while letting the remaining position run toward a further target.\n\nR-MULTIPLES — Track every trade in units of \"R\" (your initial dollar risk on that trade). A trade that nets 2× your initial risk is a \"2R\" trade; a full loss is \"-1R.\" Tracking your average R per trade over time is a far better measure of strategy quality than simply counting wins and losses.",
                "pSWzuugtQOY",
                "[{\"q\":\"In the worked example, what was the position size for a $50 risk with a 30-pip stop and $0.10 pip value?\",\"options\":[\"1.67 micro lots\",\"16.7 micro lots\",\"167 micro lots\",\"3 micro lots\"],\"correct\":1},{\"q\":\"Why can trading EUR/USD and GBP/USD together be riskier than it appears?\",\"options\":[\"They never move together\",\"They are often correlated, effectively doubling your real exposure\",\"GBP/USD has no spread\",\"EUR/USD cannot be traded with USD/CAD\"],\"correct\":1},{\"q\":\"What is an R-multiple used to track?\",\"options\":[\"The number of currency pairs traded\",\"A trade's result measured in units of your initial risk\",\"The broker's commission rate\",\"The number of pips in a standard lot\"],\"correct\":1}]"),
            new L("Trading Psychology", "15 min", true, 10,
                "Trading psychology is often said to account for up to 80% of long-term trading success. You can have a statistically sound strategy and still lose money consistently if you cannot control your emotions around it.\n\nFEAR — Fear of missing out (FOMO) causes traders to chase entries after a move has already happened, buying near the top or selling near the bottom. Fear of loss causes traders to move their stop loss further away or hold a losing trade hoping it turns around. Fear of pulling the trigger causes traders to hesitate and miss valid setups entirely.\n\nGREED — Greed causes traders to remove a take profit target mid-trade hoping for \"just a bit more,\" to increase position sizes sharply after a winning streak, and to overtrade — taking low-quality setups just to stay in the market.\n\nTHE PROFESSIONAL MINDSET — Professional traders think in probabilities across a large series of trades, not in terms of any single outcome. They know that even an excellent setup can lose, and a poor setup can win, purely due to randomness. Their focus is on executing their process correctly and consistently, not on the result of any one trade.\n\nDISCIPLINE — \"Plan your trade, trade your plan.\" Before entering any position, you should already know your exact entry, stop loss, take profit, and position size. If any one of those is undefined when you click buy or sell, you are not trading a plan — you are gambling.\n\nKEEPING A TRADING JOURNAL — Log every trade: what you saw on the chart, why you entered, how you managed it, and how you felt during the trade. Reviewing this weekly reveals patterns in both the market and your own behaviour that are impossible to see in the moment.\n\nAFTER A LOSS — Take a short break rather than immediately opening another trade to \"make it back.\" Losses are a normal, expected part of any strategy; treating each one as an emergency is what leads to the emotional spiral that destroys accounts.\n\nTHE PROBABILISTIC MINDSET — Trading psychologist Mark Douglas, author of the widely respected book Trading in the Zone, argued that consistently successful traders adopt a genuinely probabilistic mindset: accepting that any single trade has an unpredictable outcome, while trusting that a well-defined edge executed consistently over a large series of trades produces a predictable result over time. Learning to think in probabilities rather than certainties — expecting to be wrong on individual trades without it shaking confidence in the process — is central to this approach.\n\nFURTHER READING — For a deeper dive into the mental side of trading, \"Trading in the Zone\" by Mark Douglas is widely considered the definitive book on trading psychology and is a strong next step after this lesson.",
                "ZO5XZB2_X2A",
                "[{\"q\":\"What percentage of trading success is trading psychology sometimes said to account for?\",\"options\":[\"10%\",\"30%\",\"50%\",\"Up to 80%\"],\"correct\":3},{\"q\":\"What does 'plan your trade, trade your plan' mean?\",\"options\":[\"Only plan trades on weekends\",\"Know your entry, stop loss, take profit, and size before entering\",\"Change your stop loss as often as needed\",\"Always double your position size after a loss\"],\"correct\":1},{\"q\":\"What is the recommended response after taking a loss?\",\"options\":[\"Immediately open a bigger trade to recover it\",\"Take a short break rather than revenge trading\",\"Stop trading forever\",\"Increase leverage on the next trade\"],\"correct\":1}]"),
            new L("Fundamental Analysis & News Trading", "20 min", true, 11,
                "Fundamental analysis examines the underlying economic forces that drive currency values over the medium and long term, as opposed to technical analysis which studies price action itself.\n\nGDP (Gross Domestic Product) — Measures a country's total economic output. Strong GDP growth typically strengthens a currency as it signals a healthy, expanding economy that attracts investment.\n\nINTEREST RATES — Set by central banks such as the US Federal Reserve, the European Central Bank, and the Bank of England. Higher interest rates attract foreign capital seeking better returns, increasing demand for that currency. Interest rate decisions and the language used to describe future policy are arguably the single biggest driver of long-term currency direction.\n\nINFLATION (CPI / PCE) — Moderate, stable inflation is generally healthy for an economy. High or rapidly rising inflation may force a central bank to raise interest rates aggressively to cool the economy, which in turn tends to strengthen the currency in the short term.\n\nEMPLOYMENT DATA — Strong employment figures signal underlying economic health. In the US, the Non-Farm Payrolls (NFP) report — released on the first Friday of most months — is one of the most closely watched and market-moving events in all of Forex trading.\n\nTRADING AROUND NEWS — High-impact news releases cause sudden, sharp price movements within seconds. Spreads widen dramatically and slippage (getting filled at a worse price than expected) is common during these releases. Always check an economic calendar before trading, and understand that holding positions through a high-impact release carries significantly elevated risk.\n\nCENTRAL BANK LANGUAGE — Markets react not just to what a central bank does, but to what it signals about the future. \"Hawkish\" language (hinting at future rate hikes to fight inflation) is generally bullish for a currency. \"Dovish\" language (hinting at future rate cuts to support growth) is generally bearish.",
                "gX-ylmw-WGI",
                "[{\"q\":\"Which economic event is described as one of the most closely watched in Forex?\",\"options\":[\"Weekly oil inventory report\",\"US Non-Farm Payrolls (NFP)\",\"Local weather report\",\"Daily gold fixing\"],\"correct\":1},{\"q\":\"What does 'hawkish' central bank language generally signal for a currency?\",\"options\":[\"Bearish, hinting at rate cuts\",\"Bullish, hinting at future rate hikes\",\"No effect on the currency\",\"Only affects stock markets\"],\"correct\":1},{\"q\":\"Why is trading through high-impact news releases considered risky?\",\"options\":[\"Spreads narrow and slippage disappears\",\"Spreads widen dramatically and slippage is common\",\"The market closes automatically\",\"Leverage is disabled during news\"],\"correct\":1}]"),
            new L("Building a Complete Trading Strategy", "25 min", true, 12,
                "A trading strategy is a complete, rule-based system that tells you exactly when to enter a trade, when to exit, and how much to risk — removing guesswork and emotion from the decision-making process.\n\n1. MARKET SELECTION — Stick to 2-3 currency pairs you know well rather than jumping between many different instruments. Familiarity with a pair's typical behaviour is a real edge.\n\n2. TIMEFRAME STRUCTURE — Use the Daily chart to identify the overall trend and major support/resistance levels, the 4-Hour chart to time your entries within that trend, and the 1-Hour chart (or lower) for precise entry triggers.\n\n3. TREND FILTER — Only take trades in the direction of the higher timeframe trend. Counter-trend trades have a lower probability of success and should be reserved for experienced traders with a specific, tested reason for taking them.\n\n4. ENTRY TRIGGER — Define the exact, objective condition that triggers an entry, written down in plain language. Example: \"I buy EUR/USD when price pulls back to a key support level and forms a bullish engulfing candle on the 1H chart while the 50 EMA is pointing up.\"\n\n5. STOP LOSS PLACEMENT — Place your stop just beyond the price level at which your original analysis would be proven wrong — not at an arbitrary pip distance.\n\n6. TAKE PROFIT — Define your target before entering the trade, based on the next meaningful level of support/resistance, aiming for a minimum 1:2 risk-to-reward ratio.\n\n7. POSITION SIZING — Calculate your lot size using the position sizing formula so that every trade risks the same 1-2% of account balance, regardless of how far away the stop loss is.\n\nBACKTESTING — Before trading a strategy live (even in a simulator), test it against 3-6 months of historical charts. Manually count your wins, losses, average risk-to-reward, and maximum drawdown to get a realistic sense of how the strategy performs across many market conditions.\n\nTHE GOLDEN RULE — Never change your strategy's rules mid-trade based on how you feel in the moment. Review performance and refine the rules only between trading sessions, with a clear head and the full data in front of you.",
                "1APcyDafmkY",
                "[{\"q\":\"According to the lesson, what should you use the Daily chart for?\",\"options\":[\"Precise entry triggers only\",\"Identifying overall trend and major support/resistance\",\"Checking the spread\",\"Nothing — it's not used in strategy building\"],\"correct\":1},{\"q\":\"Where should a stop loss be placed according to this lesson?\",\"options\":[\"Always exactly 10 pips away\",\"Just beyond the level where your analysis would be proven wrong\",\"As close to entry as possible regardless of structure\",\"Stop losses aren't necessary with a good strategy\"],\"correct\":1},{\"q\":\"What is the 'golden rule' emphasized at the end of this lesson?\",\"options\":[\"Change your strategy mid-trade if it feels wrong\",\"Never change your strategy's rules mid-trade based on emotion\",\"Only backtest for one week\",\"Always use maximum leverage\"],\"correct\":1}]")
        };

        for (var l : lessons) {
            Lesson lesson = lessonRepository.findByTitle(l.title()).orElseGet(Lesson::new);
            lesson.setTitle(l.title());
            lesson.setDuration(l.duration());
            lesson.setPremium(l.premium());
            lesson.setOrder(l.order());
            lesson.setContent(l.content());
            lesson.setVideoId(l.videoId());
            lesson.setQuizJson(l.quiz());
            lessonRepository.save(lesson);
        }
        log.info("Lessons seeded/updated");
    }

    private void seedChallenges() {
        if (challengeRepository.count() > 0) return;

        record C(String title, String reward, String cash, boolean premium, int total) {}
        var challenges = new C[]{
            new C("First Trade",                      "First Trade Badge",   null,   false, 1),
            new C("Complete 3 Lessons",               "Scholar Badge",       null,   false, 3),
            new C("Make 5 Trades",                    "Active Trader Badge", null,   false, 5),
            new C("Achieve a Profitable Trade",       "Profit Badge",        null,   false, 1),
            new C("Weekly Trading Champion",          "1000 XP",             "$200", true,  10),
            new C("5 Consecutive Winning Trades",     "600 XP",              "$50",  true,  5),
            new C("Achieve 70% Win Rate (10 trades)", "800 XP",              "$100", true,  10),
            new C("Best Monthly P&L",                 "1500 XP",             "$150", true,  1),
            new C("Trade 5 Different Instruments",    "500 XP",              "$30",  true,  5),
        };

        for (var c : challenges) {
            Challenge ch = new Challenge();
            ch.setTitle(c.title());
            ch.setReward(c.reward());
            ch.setCashPrize(c.cash());
            ch.setPremium(c.premium());
            ch.setTotal(c.total());
            challengeRepository.save(ch);
        }
        log.info("Challenges seeded");
    }
}
