spring.application.name=admin-service
server.port=5007
spring.datasource.url=jdbc:postgresql://localhost:5432/vmlts
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:vmlts_jwt_super_secret_key_2024_X}
jwt.expiration=604800000
logging.level.com.vmlts=INFO